services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.test
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - test-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    command: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - test-network
    restart: unless-stopped

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  test-network:
    driver: bridge 